server.port: 9090

#logging.level.org.springframework: debug

spring.application.name: request-response-stateful-operation

# Confluent Local Common configuration
spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            brokers: kafka-0.kafka.confluent.svc.cluster.local:9092

spring.cloud.stream.function.definition: acs_request_transactions;mq_request_response_transactions;acs_response_transactions
spring.cloud.function.definition: acs_request_transactions;mq_request_response_transactions;acs_response_transactions

spring.cloud.stream.kafka.streams.binder.functions.acs_request_transactions.applicationId: acs_request_transactions
spring.cloud.stream.bindings.acs_request_transactions-in-0.destination: acs.request.transactions.topic
spring.cloud.stream.kafka.streams.bindings.acs_request_transactions-in-0.consumer.keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.kafka.streams.bindings.acs_request_transactions-in-0.consumer.valueSerde: org.apache.kafka.common.serialization.Serdes$BytesSerde
spring.cloud.stream.bindings.acs_request_transactions-out-0.destination: mq.request.transactions.intermediate.topic
spring.cloud.stream.kafka.streams.bindings.acs_request_transactions-out-0.producer.keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.kafka.streams.bindings.acs_request_transactions-out-0.producer.valueSerde: org.apache.kafka.common.serialization.Serdes$BytesSerde

spring.cloud.stream.kafka.streams.binder.functions.mq_request_response_transactions.applicationId: mq_request_response_transactions
spring.cloud.stream.bindings.mq_request_response_transactions-in-0.destination: mq.request.transactions.intermediate.topic
spring.cloud.stream.bindings.mq_request_response_transactions-in-0.consumer.concurrency: 1
spring.cloud.stream.kafka.streams.bindings.mq_request_response_transactions-in-0.consumer.keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.kafka.streams.bindings.mq_request_response_transactions-in-0.consumer.valueSerde: com.lbg.serdes.ACSEventSerde
spring.cloud.stream.bindings.mq_request_response_transactions-in-1.destination: mq.response.transactions.topic
spring.cloud.stream.bindings.mq_request_response_transactions-in-1.consumer.concurrency: 1
spring.cloud.stream.kafka.streams.bindings.mq_request_response_transactions-in-1.consumer.keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.kafka.streams.bindings.mq_request_response_transactions-in-1.consumer.valueSerde: com.lbg.serdes.MQEventSerde

spring.cloud.stream.kafka.streams.binder.functions.acs_response_transactions.applicationId: acs_response_transactions
spring.cloud.stream.bindings.acs_response_transactions-in-0.destination: acs.response.transactions.intermediate.topic
spring.cloud.stream.kafka.streams.bindings.acs_response_transactions-in-0.consumer.keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.kafka.streams.bindings.acs_response_transactions-in-0.consumer.valueSerde: com.lbg.serdes.MQEventSerde
spring.cloud.stream.bindings.acs_response_transactions-out-0.destination: acs.response.transactions.topic
spring.cloud.stream.kafka.streams.bindings.acs_response_transactions-out-0.producer.keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.kafka.streams.bindings.acs_response_transactions-out-0.producer.valueSerde: com.lbg.serdes.ACSEventSerde

spring.output.ansi.enabled: ALWAYS

logging.pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"

management.endpoints.web.exposure.include: "*"
#management.endpoint.loggers.enabled: true

#management.endpoints.enabled-by-default: false
management.endpoint.health.enabled: true
management.endpoint.health.probes.enabled: true
management.endpoint.health.group.liveness.additional-path: server:/livez
management.endpoint.health.group.readiness.additional-path: server:/readyz
management.endpoint.health.group.readiness.show-details: always
management.endpoint.health.group.liveness.show-details: always

management.endpoint.health.group.liveness.include: livenessState,binders