apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fpp-v3
  name: fpp-v3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fpp-v3
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fpp-v3
    spec:
      containers:
        - image: devinaction/consumer
          name: fpp-v3
          resources: { }
          livenessProbe:
            httpGet:
              path: /livez
              port: 8081
            periodSeconds: 5
            failureThreshold: 2
status: { }