apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: istio-loadbalancer
  name: istio-loadbalancer
spec:
  replicas: 4
  selector:
    matchLabels:
      app: istio-loadbalancer
  strategy: { }
  template:
    metadata:
      labels:
        app: istio-loadbalancer
    spec:
      containers:
        - image: devinaction/istio-loadbalancer
          name: istio-loadbalancer
          resources: { }
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8088
            periodSeconds: 5
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8088
            periodSeconds: 5
            failureThreshold: 5
status: { }