server.port: 9090

#logging.level.org.springframework: debug

spring.application.name: request-response-stateful-operation

# Confluent Local Common configuration
spring:
  kafka:
    bootstrap-servers: kafka-0.kafka.confluent.svc.cluster.local:9092
  cloud:
    stream:
      kafka:
        streams:
          binder:
            brokers: kafka-0.kafka.confluent.svc.cluster.local:9092

spring.cloud.stream.function.definition: topology_1

spring.cloud.stream.kafka.streams.binder.functions.topology_1.applicationId: topology_1
spring.cloud.stream.bindings.topology_1-in-0.destination: usm.request.topic
spring.cloud.stream.kafka.streams.bindings.topology_1-in-0.consumer.keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.kafka.streams.bindings.topology_1-in-0.consumer.valueSerde: com.lbg.serdes.USMEventSerde
spring.cloud.stream.bindings.topology_1-out-0.destination: acs.aggregate.request.topic
spring.cloud.stream.kafka.streams.bindings.topology_1-out-0.producer.keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.kafka.streams.bindings.topology_1-out-0.producer.valueSerde: com.lbg.serdes.ACSEventSerde

spring.output.ansi.enabled: ALWAYS

logging.pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"

management.endpoints.web.exposure.include: "*"
#management.endpoint.loggers.enabled: true

#management.endpoints.enabled-by-default: false
management.endpoint.health.enabled: true
management.endpoint.health.probes.enabled: true
management.endpoint.health.group.liveness.additional-path: server:/livez
management.endpoint.health.group.readiness.additional-path: server:/readyz
management.endpoint.health.group.readiness.show-details: always
management.endpoint.health.group.liveness.show-details: always

management.endpoint.health.group.liveness.include: livenessState,binders