apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: request-response-stateful-operation
  name: request-response-stateful-operation
spec:
  replicas: 3
  selector:
    matchLabels:
      app: request-response-stateful-operation
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: request-response-stateful-operation
    spec:
      containers:
      - image: devinaction/request-response-stateful-operation
        name: request-response-stateful-operation
        resources: {}
status: {}